sudo: required
services:
  - docker

before_install: 
  - docker build -t dbesserman/docker-react -f Dockerfile.dev .

script:
  - docker run dbesserman/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-644027365656"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
